name: log4cats
baseurl: /log4cats
description: Functional Logging
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0-RC2+6-8327aa61-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
