name: log4cats
baseurl: /log4cats
description: Functional Logging
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0+18-4d699cdb-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
