name: log4cats
baseurl: /log4cats
description: Functional Logging
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0-RC3+13-c597e0f8-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
